import os
import logging
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors

logger = logging.getLogger(__name__)

# Register Segoe UI and Roboto fonts once
def ensure_fonts():
    font_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'accounting', 'fonts')
    
    segoe_paths = {
        'SegoeUI': os.path.join(font_dir, 'segoeui.ttf'),
        'SegoeUI-Bold': os.path.join(font_dir, 'segoeuib.ttf'),
        'SegoeUI-Italic': os.path.join(font_dir, 'segoeuii.ttf'),
        'SegoeUI-BoldItalic': os.path.join(font_dir, 'segoeuiz.ttf'),
        'SegoeUI-Semibold': os.path.join(font_dir, 'seguisb.ttf'),
        'SegoeUI-Black': os.path.join(font_dir, 'seguibl.ttf'),
    }
    
    segoe_loaded = True
    for name, path in segoe_paths.items():
        if os.path.exists(path):
            try:
                pdfmetrics.registerFont(TTFont(name, path))
            except Exception as e:
                logger.warning(f"Error registering font {name}: {e}")
                segoe_loaded = False
        else:
            segoe_loaded = False

    roboto_paths = {
        'Roboto': os.path.join(font_dir, 'Roboto-Regular.ttf'),
        'Roboto-Bold': os.path.join(font_dir, 'Roboto-Bold.ttf'),
        'Roboto-Oblique': os.path.join(font_dir, 'Roboto-Italic.ttf'),
        'Roboto-BoldOblique': os.path.join(font_dir, 'Roboto-BoldItalic.ttf'),
    }
    
    roboto_loaded = True
    for name, path in roboto_paths.items():
        if os.path.exists(path):
            try:
                pdfmetrics.registerFont(TTFont(name, path))
            except Exception as e:
                logger.warning(f"Error registering font {name}: {e}")
                roboto_loaded = False
        else:
            roboto_loaded = False
            
    return segoe_loaded, roboto_loaded

SEGOE_LOADED, ROBOTO_LOADED = ensure_fonts()
FONTS_LOADED = SEGOE_LOADED or ROBOTO_LOADED


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that counts total pages and dynamically prints
    'Page X of Y' in the bottom-right footer along with doc title in bottom-left.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont('Roboto' if FONTS_LOADED else 'Helvetica', 8)
        self.setFillColor(colors.HexColor('#6B7280'))
        
        # Bottom margin footer
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(575, 18, page_str)
        
        # Left branding
        self.drawString(20, 18, "Generated by Vouch ERP — vouch-pi-one.vercel.app")
        self.restoreState()
