# Generated by Django 5.2.17 on 2026-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CA', 'Chartered Accountant'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
