# Generated by Django 5.2.17 on 2026-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('CA', 'Chartered Accountant'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
