# Generated by Django 6.1 on 2026-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
