# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_consolidate_party_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default discount percentage for this party', max_digits=5),
        ),
    ]
