# Generated by Django 5.2.17 on 2026-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_reassign_round_off_to_indirect_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='credit_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Credit terms in days (0 for Immediate)'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
