# Generated by Django 6.1 on 2026-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_ledger_credit_period_days_ledger_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
