# Generated by Django 5.2.17 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_usercompany_role'),
        ('ledgers', '0007_ledger_bank_account_number_ledger_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'is_active', 'name'], name='ledgers_led_company_f40106_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'updated_at'], name='ledgers_led_company_e0b1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'ledger_type'], name='ledgers_led_company_2e60bd_idx'),
        ),
    ]
