# Generated by Django 5.2.17 on 2026-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0008_ledger_ledgers_led_company_f40106_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_rcm',
            field=models.BooleanField(default=False, help_text='True if this ledger is an RCM Tax Liability or RCM ITC ledger'),
        ),
    ]
