# Generated by Django 5.2.17 on 2026-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0009_ledger_is_rcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='pan',
            field=models.CharField(blank=True, help_text='Party PAN (Permanent Account Number)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tds_applicable',
            field=models.BooleanField(default=False, help_text='Whether TDS deduction applies to this ledger/vendor'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tds_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default TDS rate percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tds_section',
            field=models.CharField(blank=True, help_text='Default TDS section: 194C, 194J, 194I, 194Q', max_length=20, null=True),
        ),
    ]
