# Generated by Django 5.2.17 on 2026-10-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0010_ledger_pan_ledger_tds_applicable_ledger_tds_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='is_rcm',
            field=models.BooleanField(db_default=False, default=False, help_text='True if this ledger is an RCM Tax Liability or RCM ITC ledger'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='tds_applicable',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether TDS deduction applies to this ledger/vendor'),
        ),
    ]
