# Generated by Django 6.1 on 2026-08-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='companies.company')),
                ('sales_invoice_prefix', models.CharField(default='SAL', max_length=10)),
                ('purchase_invoice_prefix', models.CharField(default='PUR', max_length=10)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
