# Generated by Django 6.1 on 2026-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='complexity_level',
            field=models.IntegerField(default=1, help_text='1: Small (1-5), 2: Medium (6-10), 3: Large (10+)'),
        ),
    ]
