# Generated by Django 6.1 on 2026-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companysettings_complexity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_ledger_mapping',
            field=models.BooleanField(default=False),
        ),
    ]
