# Generated by Django 6.1 on 2026-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companysettings_enable_ledger_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_manual_invoice_number',
            field=models.BooleanField(default=False),
        ),
    ]
