# Generated by Django 6.1 on 2026-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companysettings_enable_manual_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_advanced_item_creation',
            field=models.BooleanField(default=False),
        ),
    ]
