# Generated by Django 6.1 on 2026-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companysettings_enable_advanced_item_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='proprietor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='proprietor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='proprietor_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
