# Generated by Django 6.1 on 2026-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
