# Generated by Django 5.2.17 on 2026-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_deleted_at_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enforce_credit_limit',
            field=models.BooleanField(default=False, help_text='If True, blocks sales when credit limit exceeded; if False, only warns'),
        ),
    ]
