# Generated by Django 5.2.17 on 2026-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companysettings_enforce_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CA', 'Chartered Accountant'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], max_length=20),
        ),
    ]
