# Generated by Django 5.2.17 on 2026-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_usercompany_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='allow_negative_stock',
            field=models.BooleanField(default=True),
        ),
    ]
