# Generated by Django 5.2.17 on 2026-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_companysettings_allow_negative_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('CA', 'Chartered Accountant'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], max_length=20),
        ),
    ]
