# Generated by Django 5.2.17 on 2026-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_usercompany_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
