# Generated by Django 5.2.17 on 2026-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_logo_company_logo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
        migrations.AddField(
            model_name='company',
            name='stamp_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='document_branding',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
