# Generated by Django 6.1 on 2026-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_company_stamp_company_stamp_data_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI VPA (e.g. merchant@okhdfcbank) for dynamic QR code on invoices', max_length=100, null=True),
        ),
    ]
