# Generated by Django 5.2.17 on 2026-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_sync_company_bank_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='books_lock_date',
            field=models.DateField(blank=True, help_text='Accounting lock date: vouchers on or prior to this date cannot be created, modified, or cancelled without authorization.', null=True),
        ),
    ]
