# Generated by Django 6.1 on 2026-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='attachment_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='attachment_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
