# Generated by Django 6.1 on 2026-09-01 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_voucher_attachment_data_voucher_attachment_mime'),
        ('companies', '0008_company_bank_account_number_company_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardVoucherRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='Snapshot of invoice lines, amounts, taxes, HSN codes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING', max_length=20)),
                ('digital_signature_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_purchase_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_edi_request', to='accounting.voucher')),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edi_requests', to='companies.company')),
                ('source_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edi_requests', to='accounting.voucher')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edi_requests', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
