# Generated by Django 6.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_inwardvoucherrequest'),
        ('companies', '0009_alter_company_address_alter_company_city_and_more'),
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], default='DR', max_length=2)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('closing_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], default='DR', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], max_length=20)),
                ('prefix', models.CharField(default='INV', max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='companies.company')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voucher',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.financialyear'),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('company', 'financial_year', 'voucher_number')},
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'financial_year', 'voucher_number'], name='accounting__company_9ea5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_date'], name='accounting__company_97c9bc_idx'),
        ),
        migrations.AddField(
            model_name='ledgerbalance',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_balances', to='accounting.financialyear'),
        ),
        migrations.AddField(
            model_name='ledgerbalance',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_balances', to='ledgers.ledger'),
        ),
        migrations.AddField(
            model_name='vouchersequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sequences', to='companies.company'),
        ),
        migrations.AddField(
            model_name='vouchersequence',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='accounting.financialyear'),
        ),
        migrations.AlterUniqueTogether(
            name='financialyear',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='ledgerbalance',
            unique_together={('ledger', 'financial_year')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchersequence',
            unique_together={('company', 'financial_year', 'voucher_type')},
        ),
    ]
