# Generated by Django 6.1 on 2026-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_ledgerbalance_vouchersequence_financialyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='is_split_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vouchersequence',
            name='method',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic (Sequential)'), ('MANUAL', 'Manual Override')], default='AUTOMATIC', max_length=20),
        ),
        migrations.AddField(
            model_name='vouchersequence',
            name='starting_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vouchersequence',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vouchersequence',
            name='width',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
