# Generated by Django 5.2.17 on 2026-09-09 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_restore_pix_b55_mrp'),
        ('companies', '0011_company_deleted_at_company_is_active'),
        ('inventory', '0008_product_costing_method'),
        ('ledgers', '0005_reassign_round_off_to_indirect_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('command_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='companies.company'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_items', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('CONTRA', 'Contra'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('JOURNAL', 'Journal'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'ledger', 'created_at'], name='accounting__company_876b47_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', 0)), name='chk_ledger_entry_debit_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', 0)), name='chk_ledger_entry_credit_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gt', 0), ('credit_amount__gt', 0), _negated=True), name='chk_ledger_entry_not_both_dr_and_cr'),
        ),
        migrations.AddConstraint(
            model_name='voucheritem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_voucher_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucheritem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='chk_voucher_item_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucheritem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='chk_voucher_item_discount_pct_range'),
        ),
        migrations.AddField(
            model_name='offlinecommand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_commands', to='companies.company'),
        ),
        migrations.AddField(
            model_name='offlinecommand',
            name='result_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_command', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='offlinecommand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_received', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_made', to='accounting.voucher'),
        ),
        migrations.AddIndex(
            model_name='offlinecommand',
            index=models.Index(fields=['company', 'command_type', 'status'], name='accounting__company_3fcf88_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['company', 'payment_voucher'], name='accounting__company_428678_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['company', 'invoice_voucher'], name='accounting__company_ec964e_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='chk_payment_allocation_positive'),
        ),
    ]
