# Generated by Django 6.1 on 2026-09-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_offlinecommand_paymentallocation_ledgerentry_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinecommand',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offlinecommand',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinecommand',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='corrects_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_by_vouchers', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='external_invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversal_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_vouchers', to='accounting.voucher'),
        ),
        migrations.AlterField(
            model_name='offlinecommand',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed'), ('CORRECTED', 'Corrected')], default='DRAFT', max_length=20),
        ),
    ]
