# Generated by Django 6.1 on 2026-09-10 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_offlinecommand_error_code_offlinecommand_failed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='correction_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='correction_type',
            field=models.CharField(blank=True, choices=[('CLERICAL', 'Clerical / Typo'), ('QUANTITY', 'Wrong Quantity'), ('RATE', 'Wrong Price / Rate'), ('PRODUCT', 'Wrong Product'), ('CUSTOMER', 'Wrong Customer Details'), ('GST', 'Wrong GST'), ('DATE', 'Wrong Date'), ('PAYMENT', 'Payment Adjustment'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='accounting.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Superseded'), ('REVERSED', 'Reversed'), ('CORRECTED', 'Corrected')], default='DRAFT', max_length=20),
        ),
    ]
