# Generated by Django 5.2.17 on 2026-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_voucher_corrected_at_voucher_corrected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('CONTRA', 'Contra'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('JOURNAL', 'Journal'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('OPENING', 'Opening Balance'), ('OPENING_INVOICE', 'Opening Invoice'), ('OPENING_BILL', 'Opening Bill')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vouchersequence',
            name='voucher_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('OPENING', 'Opening Balance'), ('OPENING_INVOICE', 'Opening Invoice'), ('OPENING_BILL', 'Opening Bill')], max_length=20),
        ),
    ]
