# Generated by Django 6.1 on 2026-09-10 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_voucher_due_date_alter_voucher_voucher_type_and_more'),
        ('companies', '0012_companysettings_enforce_credit_limit'),
        ('ledgers', '0006_ledger_credit_period_days_ledger_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV Statement'), ('XLSX', 'Excel Spreadsheet (XLSX)'), ('XLS', 'Excel Spreadsheet (XLS)'), ('PDF', 'PDF Statement'), ('IMAGE', 'Scanned Statement / Image')], default='CSV', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial with Warnings'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('unresolved_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='ledgers.ledger')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_imports', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('normalized_narration', models.CharField(db_index=True, max_length=500)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('extraction_confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('MATCHED_AUTO', 'Matched (Automatic)'), ('MATCHED_SUGGESTED', 'Matched (Suggested)'), ('UNRESOLVED', 'Unresolved'), ('RECONCILED', 'Reconciled'), ('IGNORED', 'Ignored')], db_index=True, default='UNPROCESSED', max_length=30)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('match_notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='ledgers.ledger')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='companies.company')),
                ('matched_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_bank_transactions', to='accounting.voucher')),
                ('matched_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_transactions', to='ledgers.ledger')),
                ('matched_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_bank_transactions', to='accounting.voucher')),
                ('statement_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.bankstatementimport')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=255)),
                ('normalized_pattern', models.CharField(db_index=True, max_length=255)),
                ('mapping_type', models.CharField(choices=[('UPI', 'UPI ID'), ('BANK_ACCOUNT', 'Bank Account / IFSC'), ('NARRATION', 'Narration Keyword / Entity'), ('EXPENSE_CATEGORY', 'Expense Category'), ('RECURRING_CHARGE', 'Recurring Charge')], default='NARRATION', max_length=50)),
                ('confirmed_by_user', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_mappings', to='companies.company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_mappings', to='ledgers.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('TRIAL_BALANCE', 'Trial Balance Equilibrium'), ('WRONG_PARTY', 'Possible Wrong Party'), ('DUPLICATE', 'Duplicate Invoices/Bills'), ('BANK', 'Bank Reconciliation Mismatch'), ('PAYMENT', 'Payment Allocation Anomaly'), ('GST', 'GST Rate or State Mismatch'), ('INVENTORY', 'Inventory & Stock Discrepancy'), ('OPENING_BALANCE', 'Opening Balance Discrepancy'), ('NUMBERING', 'Voucher Numbering Sequence'), ('UNUSUAL_ACTIVITY', 'Unusual Business Activity')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('expected_state', models.TextField(blank=True)),
                ('actual_state', models.TextField(blank=True)),
                ('probable_cause', models.TextField(blank=True)),
                ('suggested_action', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.9)),
                ('fix_action', models.CharField(blank=True, max_length=50, null=True)),
                ('fix_preview', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_findings', to='companies.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_resolved', 'severity'], name='accounting__company_9c54cf_idx'), models.Index(fields=['company', 'category'], name='accounting__company_9a1c7e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['company', 'bank_ledger', '-created_at'], name='accounting__company_d00590_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='accounting__company_b4be43_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'status'], name='accounting__company_ae204a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'reference_number'], name='accounting__company_601bda_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'bank_ledger'], name='accounting__company_3d23a7_idx'),
        ),
        migrations.AddIndex(
            model_name='partymapping',
            index=models.Index(fields=['company', 'mapping_type', 'normalized_pattern'], name='accounting__company_edec96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partymapping',
            unique_together={('company', 'normalized_pattern', 'mapping_type')},
        ),
    ]
