# Generated by Django 5.2.17 on 2026-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_bankstatementimport_banktransaction_partymapping_and_more'),
        ('companies', '0012_companysettings_enforce_credit_limit'),
        ('ledgers', '0007_ledger_bank_account_number_ledger_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'fingerprint'], name='accounting__company_fbfde8_idx'),
        ),
    ]
