# Generated by Django 5.2.17 on 2026-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_banktransaction_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='balance_chain_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='calculated_closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='discrepancy_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
