# Generated by Django 5.2.17 on 2026-09-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_bankstatementimport_balance_chain_valid_and_more'),
        ('companies', '0012_companysettings_enforce_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('operation', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='companies.company')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'id'], name='accounting__company_cbcae9_idx')],
            },
        ),
    ]
