# Generated by Django 5.2.17 on 2026-09-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_syncevent'),
        ('companies', '0012_companysettings_enforce_credit_limit'),
        ('ledgers', '0007_ledger_bank_account_number_ledger_bank_ifsc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='accounting__company_3d23a7_idx',
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='excluded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_statement_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='is_excluded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='statement_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='statement_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='excluded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_bank_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_excluded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('MATCHED_AUTO', 'Matched (Automatic)'), ('MATCHED_SUGGESTED', 'Matched (Suggested)'), ('UNRESOLVED', 'Unresolved'), ('RECONCILED', 'Reconciled'), ('IGNORED', 'Ignored'), ('EXCLUDED', 'Excluded')], db_index=True, default='UNPROCESSED', max_length=30),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['company', 'is_excluded'], name='accounting__company_964a04_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'is_excluded', 'status'], name='accounting__company_994df7_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'bank_ledger', 'transaction_date'], name='accounting__company_25d753_idx'),
        ),
    ]
