# Generated by Django 5.2.17 on 2026-09-13 15:10

from django.conf import settings
from django.db import migrations, models


def clean_invalid_bank_transactions(apps, schema_editor):
    BankTransaction = apps.get_model('accounting', 'BankTransaction')
    from decimal import Decimal
    for tx in BankTransaction.objects.filter(debit_amount__gt=0, credit_amount__gt=0):
        desc = (tx.description or '').lower()
        if 'debit' in desc or 'charge' in desc or 'fee' in desc:
            tx.credit_amount = Decimal('0.00')
        elif 'credit' in desc or 'deposit' in desc:
            tx.debit_amount = Decimal('0.00')
        elif tx.balance is not None and tx.credit_amount == tx.balance:
            tx.credit_amount = Decimal('0.00')
        else:
            tx.credit_amount = Decimal('0.00')
        tx.save(update_fields=['debit_amount', 'credit_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_remove_banktransaction_accounting__company_3d23a7_idx_and_more'),
        ('companies', '0012_companysettings_enforce_credit_limit'),
        ('ledgers', '0007_ledger_bank_account_number_ledger_bank_ifsc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clean_invalid_bank_transactions, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', 0), ('credit_amount__gte', 0)), name='bank_tx_non_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gt', 0), ('debit_amount__gt', 0), _negated=True), name='bank_tx_not_both_debit_and_credit'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gt', 0), ('credit_amount__gt', 0), _connector='OR'), name='bank_tx_at_least_one_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint__isnull', False), models.Q(('fingerprint', ''), _negated=True)), fields=('company', 'bank_ledger', 'fingerprint'), name='unique_company_bank_tx_fingerprint'),
        ),
    ]
