# Generated by Django 5.2.17 on 2026-09-19 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_backfill_ledgerentry_company'),
        ('companies', '0013_alter_usercompany_role'),
        ('inventory', '0008_product_costing_method'),
        ('ledgers', '0007_ledger_bank_account_number_ledger_bank_ifsc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchersequence',
            name='voucher_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('OPENING', 'Opening Balance'), ('OPENING_INVOICE', 'Opening Invoice'), ('OPENING_BILL', 'Opening Bill'), ('PROFORMA', 'Proforma Invoice'), ('QUOTATION', 'Quotation / Estimate')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proforma_type', models.CharField(choices=[('PROFORMA', 'Proforma Invoice'), ('QUOTATION', 'Quotation / Estimate')], default='PROFORMA', max_length=20)),
                ('proforma_number', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('buyer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('buyer_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cartage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('CONVERTED', 'Converted to Tax Invoice'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cgst_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledgers.ledger')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='companies.company')),
                ('converted_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proforma', to='accounting.voucher')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proformas', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='accounting.financialyear')),
                ('igst_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledgers.ledger')),
                ('party_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoices', to='ledgers.ledger')),
                ('sales_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledgers.ledger')),
                ('sgst_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledgers.ledger')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_items', to='inventory.product')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.proformainvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['company', 'proforma_number'], name='accounting__company_6a2522_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['company', 'date'], name='accounting__company_5c22f1_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['company', 'status'], name='accounting__company_efceaf_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['company', 'proforma_type'], name='accounting__company_c925ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proformainvoice',
            unique_together={('company', 'financial_year', 'proforma_number')},
        ),
    ]
