# Generated by Django 5.2.17 on 2026-09-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_vouchersequence_voucher_type_proformainvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='itc_held_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='itc_match_status',
            field=models.CharField(choices=[('UNCHECKED', 'Unchecked'), ('MATCHED', 'Matched in 2B'), ('MISMATCHED', 'Mismatch with 2B'), ('MISSING_IN_2B', 'Missing in 2B')], default='UNCHECKED', max_length=30),
        ),
        migrations.AddField(
            model_name='voucher',
            name='itc_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
