# Generated by Django 5.2.17 on 2026-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_voucher_buyer_email_voucher_itc_held_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='itc_held_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='itc_match_status',
            field=models.CharField(blank=True, choices=[('UNCHECKED', 'Unchecked'), ('MATCHED', 'Matched in 2B'), ('MISMATCHED', 'Mismatch with 2B'), ('MISSING_IN_2B', 'Missing in 2B')], default='UNCHECKED', max_length=30, null=True),
        ),
    ]
