# Generated by Django 5.2.17 on 2026-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_voucher_itc_held_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingfinding',
            name='category',
            field=models.CharField(choices=[('TRIAL_BALANCE', 'Trial Balance Equilibrium'), ('WRONG_PARTY', 'Possible Wrong Party'), ('DUPLICATE', 'Duplicate Invoices/Bills'), ('BANK', 'Bank Reconciliation Mismatch'), ('PAYMENT', 'Payment Allocation Anomaly'), ('GST', 'GST Rate or State Mismatch'), ('INVENTORY', 'Inventory & Stock Discrepancy'), ('OPENING_BALANCE', 'Opening Balance Discrepancy'), ('NUMBERING', 'Voucher Numbering Sequence'), ('UNUSUAL_ACTIVITY', 'Unusual Business Activity'), ('MARGIN_RISK', 'Profit Margin & Pricing Alerts'), ('LIQUIDITY', 'Cash & Bank Liquidity Safety')], db_index=True, max_length=50),
        ),
    ]
