# Generated by Django 5.2.17 on 2026-09-28 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_accountingfinding_category'),
        ('companies', '0015_alter_usercompany_role'),
        ('ledgers', '0007_ledger_bank_account_number_ledger_bank_ifsc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'status', 'voucher_date'], name='accounting__company_d7d5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'updated_at'], name='accounting__company_b9e743_idx'),
        ),
    ]
