# Generated by Django 6.1 on 2026-09-30 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_voucher_accounting__company_d7d5ec_idx_and_more'),
        ('companies', '0017_company_stamp_company_stamp_data_company_website_and_more'),
        ('ledgers', '0008_ledger_ledgers_led_company_f40106_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'ledger'], name='accounting__company_e756f8_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['voucher', 'ledger'], name='accounting__voucher_47b6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'ledger', 'voucher'], name='accounting__company_a733a9_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'status'], name='accounting__company_1e027a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'party_ledger', 'voucher_date'], name='accounting__company_9d90a5_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'party_ledger', 'status'], name='accounting__company_dea64a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_type', 'voucher_date'], name='accounting__company_00135f_idx'),
        ),
    ]
