# Generated by Django 5.2.17 on 2026-10-02 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_ledgerentry_accounting__company_e756f8_idx_and_more'),
        ('companies', '0018_company_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocation_tasks', to='companies.company')),
                ('payment_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_tasks', to='accounting.voucher')),
                ('preferred_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_allocation_tasks', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='accounting__company_af9f06_idx'), models.Index(fields=['payment_voucher', 'status'], name='accounting__payment_fb090f_idx')],
            },
        ),
    ]
