# Generated by Django 5.2.17 on 2026-10-03 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_paymentallocationtask'),
        ('companies', '0018_company_upi_id'),
        ('ledgers', '0008_ledger_ledgers_led_company_f40106_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_type', 'status', 'voucher_date'], name='accounting__company_4b7903_idx'),
        ),
    ]
