# Generated by Django 5.2.17 on 2026-10-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_voucher_accounting__company_4b7903_idx'),
        ('companies', '0018_company_upi_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inwardvoucherrequest',
            constraint=models.UniqueConstraint(fields=('source_voucher', 'target_company'), name='unique_edi_request_per_voucher_target'),
        ),
    ]
