# Generated by Django 5.2.17 on 2026-10-06 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_unique_edi_request_constraint'),
        ('companies', '0019_auto_sync_company_bank_ledgers'),
        ('ledgers', '0008_ledger_ledgers_led_company_f40106_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCompanyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('TRANSFER', 'Funds Transfer (Bank/Cash)'), ('EXPENSE_PAID_ON_BEHALF', 'Expense Paid on Behalf'), ('SALE_PURCHASE', 'Inter-Company Sale / Purchase'), ('TRIANGULAR_SETTLEMENT', 'Triangular Cross-Entity Settlement')], default='TRANSFER', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_date', models.DateField()),
                ('narration', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Mirror Entry'), ('ACCEPTED', 'Accepted & Posted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_intercompany_entries', to=settings.AUTH_USER_MODEL)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_intercompany_entries', to='companies.company')),
                ('source_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_intercompany_entries', to='accounting.voucher')),
                ('suggested_target_credit_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledgers.ledger')),
                ('suggested_target_debit_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledgers.ledger')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_intercompany_entries', to='companies.company')),
                ('target_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_intercompany_entries', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_company', 'status'], name='accounting__target__5745ce_idx'), models.Index(fields=['source_company', 'status'], name='accounting__source__26c92b_idx')],
            },
        ),
    ]
