# Generated by Django 5.2.17 on 2026-10-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_intercompanyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_reverse_charge',
            field=models.BooleanField(db_index=True, default=False, help_text='Reverse Charge Mechanism (RCM) applicable under GST Section 9(3) or 9(4)'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='original_invoice',
            field=models.ForeignKey(blank=True, help_text='Original invoice referenced by Credit/Debit Note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_debit_notes', to='accounting.voucher'),
        ),
    ]
