# Generated by Django 5.2.17 on 2026-10-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_voucher_is_reverse_charge_voucher_original_invoice'),
        ('ledgers', '0010_ledger_pan_ledger_tds_applicable_ledger_tds_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total TDS deducted on this voucher', max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='tds_ledger',
            field=models.ForeignKey(blank=True, help_text='Ledger tracking TDS Payable for this voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_vouchers', to='ledgers.ledger'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='tds_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TDS rate percentage applied', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS section applied (e.g. 194C, 194J, 194Q)', max_length=20, null=True),
        ),
    ]
