# Generated by Django 5.2.17 on 2026-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_voucher_tds_amount_voucher_tds_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='adjusted_advance_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST advance tax knocked off by this allocation for GSTR-1 Table 11B', max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='advance_adjusted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative advance knocked off against tax invoices', max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='advance_cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='advance_igst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='advance_sgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='advance_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total GST tax component included in advance', max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='advance_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='GST rate applicable on the advance', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_advance',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this receipt/payment represents an Advance subject to GST advance rules'),
        ),
    ]
