# Generated by Django 5.2.17 on 2026-10-07 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_paymentallocation_adjusted_advance_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentallocation',
            name='adjusted_advance_tax',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='GST advance tax knocked off by this allocation for GSTR-1 Table 11B', max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='advance_adjusted_amount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='Cumulative advance knocked off against tax invoices', max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='advance_cgst',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='advance_igst',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='advance_sgst',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='advance_tax_amount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='Total GST tax component included in advance', max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='advance_tax_rate',
            field=models.DecimalField(blank=True, db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='GST rate applicable on the advance', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_advance',
            field=models.BooleanField(db_default=False, db_index=True, default=False, help_text='True if this receipt/payment represents an Advance subject to GST advance rules'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_reverse_charge',
            field=models.BooleanField(db_default=False, db_index=True, default=False, help_text='Reverse Charge Mechanism (RCM) applicable under GST Section 9(3) or 9(4)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='tds_amount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='Total TDS deducted on this voucher', max_digits=15),
        ),
    ]
