# Generated by Django 5.2.17 on 2026-09-21 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0027_alter_voucher_itc_held_amount_and_more'),
        ('companies', '0014_alter_companysettings_allow_negative_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('share_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('STATEMENT', 'Statement'), ('DOCUMENT', 'Document')], default='INVOICE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentShareEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded'), ('EMAILED', 'Emailed'), ('WHATSAPP_SHARED', 'WhatsApp Shared'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], max_length=30)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.documentshare')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment Voucher'), ('RECEIPT', 'Receipt Voucher'), ('CONTRA', 'Contra Voucher'), ('JOURNAL', 'Journal Voucher'), ('CUSTOMER_STATEMENT', 'Customer Statement'), ('SUPPLIER_STATEMENT', 'Supplier Statement'), ('LEDGER', 'Ledger Statement'), ('TRIAL_BALANCE', 'Trial Balance'), ('PROFIT_AND_LOSS', 'Profit & Loss'), ('BALANCE_SHEET', 'Balance Sheet')], db_index=True, max_length=40)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('document_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('document_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('snapshot_json', models.JSONField(help_text='Canonical Document DTO (JSON only, no binary or base64 PDF)')),
                ('template_code', models.CharField(default='gst_invoice_classic', max_length=50)),
                ('template_version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_snapshots', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentshare',
            name='document_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.documentsnapshot'),
        ),
        migrations.CreateModel(
            name='DocumentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_audit_events', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_audit_events', to=settings.AUTH_USER_MODEL)),
                ('document_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='documents.documentsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('document_type', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EDIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('receiver_gstin', models.CharField(db_index=True, max_length=15)),
                ('payload', models.JSONField(help_text='Standardized canonical EDI payload for invoice import')),
                ('payload_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edi_document', to='documents.documentsnapshot')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_edi_documents', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EDIExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SHARED', 'Shared'), ('VIEWED', 'Viewed'), ('IMPORT_INITIATED', 'Import Initiated'), ('DRAFT_CREATED', 'Draft Created'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_purchase_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_exchanges', to='accounting.voucher')),
                ('edi_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='documents.edidocument')),
                ('target_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_edi_exchanges', to='companies.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentsnapshot',
            index=models.Index(fields=['company', 'document_type', 'source_id'], name='documents_d_company_a72631_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsnapshot',
            index=models.Index(fields=['company', 'document_date'], name='documents_d_company_4066fd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsnapshot',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='documents_d_company_928af6_idx'),
        ),
        migrations.AddIndex(
            model_name='ediexchange',
            index=models.Index(fields=['target_company', 'status'], name='documents_e_target__b612c9_idx'),
        ),
    ]
