# Generated by Django 6.1 on 2026-08-27 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_id', models.UUIDField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='inventory.warehouse')),
            ],
        ),
    ]
