# Generated by Django 6.1 on 2026-08-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_brand_productcategory_gst_rate_and_more'),
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alternate_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='min_selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='override_gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='override_hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='track_batches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='track_serial_numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaler_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='purchase_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_purchases', to='ledgers.ledger'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sales_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_sales', to='ledgers.ledger'),
        ),
    ]
