# Generated by Django 6.1 on 2026-09-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryentry_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price_from_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
