# Generated by Django on 2026-09-07

from django.db import migrations


def run_deduplication(apps, schema_editor):
    from apps.inventory.services.normalization_service import combine_and_deduplicate_inventory
    # Execute deduplication across all companies, normalizing names to 'A 32', 'B 92',
    # summing stock, re-linking vouchers, and ensuring invoice tags are preserved.
    report = combine_and_deduplicate_inventory(company_name=None, dry_run=False)
    print(
        f"\n[MIGRATION] Inventory deduplication complete: "
        f"{report['total_merged_groups']} groups merged, "
        f"{report['total_deleted_duplicates']} duplicates removed, "
        f"{report['total_renamed_items']} items normalized, "
        f"{report['total_invoice_tags_set']} invoice tags applied."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_purchase_price_from_invoice'),
        ('accounting', '0005_financialyear_is_split_archived_and_more'),
    ]

    operations = [
        migrations.RunPython(run_deduplication, reverse_code=migrations.RunPython.noop),
    ]
