# Generated by Django on 2026-09-07

from django.db import migrations


def merge_prefixed_duplicates(apps, schema_editor):
    try:
        from apps.inventory.services.normalization_service import combine_and_deduplicate_inventory
        report = combine_and_deduplicate_inventory(company_name=None, dry_run=False)
        print(
            f"\n[MIGRATION 0007] Category-prefixed inventory deduplication complete: "
            f"{report['total_merged_groups']} groups merged, "
            f"{report['total_deleted_duplicates']} duplicates removed, "
            f"{report['total_renamed_items']} items normalized, "
            f"{report['total_invoice_tags_set']} invoice tags applied."
        )
    except Exception as e:
        print(f"\n[MIGRATION 0007] Skipping inventory deduplication during migration: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_deduplicate_and_combine_belting_items'),
    ]

    operations = [
        migrations.RunPython(merge_prefixed_duplicates, reverse_code=migrations.RunPython.noop),
    ]
