# Generated by Django on 2026-09-07

from django.db import migrations


def merge_prefixed_duplicates(apps, schema_editor):
    from apps.inventory.services.normalization_service import combine_and_deduplicate_inventory
    # Execute category-aware deduplication across all companies, merging items like
    # 'V Belt B34', 'V Belt B79', 'V BELTS B 72' into canonical 'B 34', 'B 79', 'B 72',
    # aggregating stock, re-linking voucher items and inventory entries, and keeping invoice tags.
    report = combine_and_deduplicate_inventory(company_name=None, dry_run=False)
    print(
        f"\n[MIGRATION 0007] Category-prefixed inventory deduplication complete: "
        f"{report['total_merged_groups']} groups merged, "
        f"{report['total_deleted_duplicates']} duplicates removed, "
        f"{report['total_renamed_items']} items normalized, "
        f"{report['total_invoice_tags_set']} invoice tags applied."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_deduplicate_and_combine_belting_items'),
    ]

    operations = [
        migrations.RunPython(merge_prefixed_duplicates, reverse_code=migrations.RunPython.noop),
    ]
