# Generated by Django 5.2.17 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_usercompany_role'),
        ('inventory', '0008_product_costing_method'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['company', 'product', 'created_at'], name='inventory_i_company_8e4265_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['company', 'voucher_id'], name='inventory_i_company_459cda_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active', 'name'], name='inventory_p_company_d9d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'updated_at'], name='inventory_p_company_0b8c7b_idx'),
        ),
    ]
