"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

if DEBUG:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])
else:
    default_hosts = [
        'api.vouch.in',
        'app.vouch.in',
        'vouch.in',
        'www.vouch.in',
        'vouch-api-752s.onrender.com',
        'localhost',
        '127.0.0.1',
    ]
    render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if render_hostname and render_hostname not in default_hosts:
        default_hosts.append(render_hostname)
    configured_hosts = env.list('ALLOWED_HOSTS', default=default_hosts)
    # Security Invariant: Never permit wildcard '*' in production
    ALLOWED_HOSTS = [h.strip() for h in configured_hosts if h.strip() and h.strip() != '*']
    if not ALLOWED_HOSTS:
        raise ValueError("Production deployment error: ALLOWED_HOSTS cannot be empty or contain wildcard '*' when DEBUG=False.")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'apps.accounts',
    'apps.companies',
    'apps.ledgers',
    'apps.accounting',
    'apps.protocol',
    'apps.inventory',
    'apps.gst',
    'apps.analytics',
    'apps.audit',
    'apps.documents',
    'apps.notifications',
    'apps.superadmin',
    'apps.common',
]

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '1200/minute',
        'sync': '180/minute',
        'auth': '30/minute',
    },
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
}

import sys
if 'test' in sys.argv:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'anon': '100000/day',
        'user': '100000/day',
        'sync': '100000/day',
        'auth': '100000/day',
    }


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'apps.common.logging.RequestCorrelationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'apps.common.client_context.ClientContextMiddleware',
    'apps.common.idempotency.IdempotencyMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': env.db('DATABASE_URL', default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'))
}

import sys
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test_db.sqlite3',
    }



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Celery Configuration
CELERY_BROKER_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/0')
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=DEBUG)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Automated Nightly Celery Beat Schedule (02:00 AM IST)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'nightly-disaster-recovery-backup': {
        'task': 'apps.accounting.tasks.automated_nightly_backup_task',
        'schedule': crontab(hour=20, minute=30),  # 20:30 UTC = 02:00 AM IST
        'kwargs': {'upload_s3': True, 'encrypt': True},
    },
}

# Off-site Disaster Recovery & Cloud Storage Settings
BACKUP_RETENTION_DAYS = env.int('BACKUP_RETENTION_DAYS', default=7)
BACKUP_ENCRYPTION_KEY = env('BACKUP_ENCRYPTION_KEY', default=SECRET_KEY)
BACKUP_S3_BUCKET = env('BACKUP_S3_BUCKET', default=None)
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default=None)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default=None)
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='ap-south-1')

from datetime import timedelta

SUPERADMIN_EMAILS = env.list('SUPERADMIN_EMAILS', default=['prakharssa@gmail.com'])

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

from corsheaders.defaults import default_headers, default_methods

# Cross-Origin Resource Sharing (CORS) & CSRF
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOW_CREDENTIALS = True


CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# Parse and normalize CORS origins (strip whitespace and trailing slashes)
_raw_cors_origins = env.list('CORS_ALLOWED_ORIGINS', default=[
    'https://vouch-pi-one.vercel.app',
    'https://vouchapp.in',
    'https://www.vouchapp.in',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
])
CORS_ALLOWED_ORIGINS = [o.strip().rstrip('/') for o in _raw_cors_origins if o.strip()]
# Guarantee the primary production Vercel origin is always authorized
if 'https://vouch-pi-one.vercel.app' not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append('https://vouch-pi-one.vercel.app')

CORS_ALLOW_METHODS = list(default_methods)
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-company-id',
    'company-id',
    'x-financial-year',
    'x-financial-year-id',
    'financial-year-id',
    'x-period',
    'x-csrftoken',
    'x-requested-with',
    'authorization',
    'content-type',
    'accept',
    'origin',
    'user-agent',
    'dnt',
    'cache-control',
    'x-confirmation-password',
    'x-idempotency-key',
    'idempotency-key',
    'x-client-type',
    'x-app-version',
    'x-device-id',
    'x-sync-cursor',
]
CORS_EXPOSE_HEADERS = ['X-Idempotent-Replay', 'X-Idempotency-Key', 'X-Server-Version', 'X-API-Contract', 'Retry-After']

CSRF_TRUSTED_ORIGINS = [
    'https://vouch-pi-one.vercel.app',
    'https://vouch-api-752s.onrender.com',
    'https://vouchapp.in',
    'https://www.vouchapp.in',
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8000',
]
render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_hostname and f'https://{render_hostname}' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_hostname}')

# Security & Reverse Proxy Settings (Production Hardening)
if not DEBUG:
    # Render / reverse proxy HTTPS termination header
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Secure Cookies over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HTTP Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Upload limits (50 MB) to prevent RequestDataTooBig on manufacturer price lists and high-res bills
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Email Configuration
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Vouch Invoicing <billing@vouchapp.in>')

# Frontend URL for viral claim / invitation links
FRONTEND_URL = env('FRONTEND_URL', default='https://vouch-pi-one.vercel.app' if not DEBUG else 'http://localhost:3000')




# Web Push VAPID Settings (Environment Driven - Zero Hardcoded Private Keys)
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_SUBJECT = os.environ.get('VAPID_SUBJECT', 'mailto:admin@vouchapp.in')

# Production Structured Observability & PII Masking
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'pii_masking': {
            '()': 'apps.common.logging.PIIMaskingFilter',
        },
    },
    'formatters': {
        'structured_json': {
            '()': 'apps.common.logging.StructuredJSONFormatter',
        },
        'standard': {
            'format': '%(asctime)s [%(levelname)s] [%(name)s] %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'structured_json' if not DEBUG else 'standard',
            'filters': ['pii_masking'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'vouch': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'vouch.observability': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'vouch.access': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

