# Generated by Django 5.2.17 on 2026-10-01 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('protocol_version', models.CharField(default='1.0', max_length=10)),
                ('state_version', models.IntegerField(default=1)),
                ('source_company_id', models.CharField(max_length=100)),
                ('destination_company_id', models.CharField(max_length=100)),
                ('canonical_payload', models.JSONField(help_text='The immutable Canonical Transaction payload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'protocol_transactions',
            },
        ),
        migrations.CreateModel(
            name='EntityMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_id', models.CharField(max_length=100, unique=True)),
                ('source_company_id', models.CharField(max_length=100)),
                ('destination_company_id', models.CharField(max_length=100)),
                ('foreign_sku', models.CharField(max_length=100)),
                ('local_sku', models.CharField(max_length=100)),
                ('mapping_version', models.IntegerField(default=1)),
                ('confidence_level', models.CharField(max_length=50)),
                ('approval_state', models.CharField(max_length=50)),
                ('conversion_multiplier', models.FloatField(default=1.0)),
                ('hsn_override', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'protocol_entity_mappings',
                'unique_together': {('source_company_id', 'destination_company_id', 'foreign_sku', 'mapping_version')},
            },
        ),
        migrations.CreateModel(
            name='CryptographicCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_hash', models.CharField(max_length=128, unique=True)),
                ('operation_state_root', models.CharField(max_length=128)),
                ('previous_commitment_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('signature', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='protocol.protocoltransaction')),
            ],
            options={
                'db_table': 'protocol_commitments',
            },
        ),
        migrations.CreateModel(
            name='ProtocolOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('replica_id', models.CharField(max_length=100)),
                ('operation_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('logical_timestamp', models.BigIntegerField()),
                ('parents', models.JSONField(default=list)),
                ('payload_hash', models.CharField(max_length=128)),
                ('signature', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='protocol.protocoltransaction')),
            ],
            options={
                'db_table': 'protocol_operations',
                'ordering': ['logical_timestamp'],
                'unique_together': {('operation_id', 'replica_id')},
            },
        ),
    ]
