# Generated by Django 5.2.17 on 2026-10-01 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdiSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('current_state', models.CharField(db_index=True, default='DISCOVER', max_length=50)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('initiator_replica_id', models.CharField(blank=True, max_length=100, null=True)),
                ('responder_replica_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('transition_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'protocol_edi_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
