# Generated by Django 5.2.17 on 2026-10-01 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_edisession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolBridgeExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('base_voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_vouchers', models.JSONField(default=list)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'protocol_bridge_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
