# Generated by Django 5.2.17 on 2026-10-01 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_protocolconsumednonce_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceKeyRotationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_public_key_hex', models.CharField(max_length=128)),
                ('old_key_id', models.CharField(max_length=100)),
                ('new_public_key_hex', models.CharField(max_length=128)),
                ('new_key_id', models.CharField(max_length=100)),
                ('authorization_method', models.CharField(max_length=50)),
                ('rotation_signature', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_history', to='protocol.authorizeddevice')),
                ('rotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'protocol_device_key_rotations',
                'ordering': ['-created_at'],
            },
        ),
    ]
