# Generated by Django 5.2.17 on 2026-09-13 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0022_banktransaction_bank_tx_non_negative_amounts_and_more'),
        ('companies', '0012_companysettings_enforce_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTTaxpayerCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, default='', max_length=255)),
                ('state_code', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('taxpayer_type', models.CharField(default='Regular', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGSTConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MOCK', 'Mock / Sandbox Provider (Offline & Testing)'), ('CLEAR', 'Clear (ClearTax API Gateway)'), ('MASTERS_INDIA', 'Masters India GST Gateway'), ('CASHFREE', 'Cashfree Verification Gateway'), ('NIC_DIRECT', 'Direct NIC API (Government Portal)')], default='MOCK', max_length=30)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('eway_username', models.CharField(blank=True, default='', max_length=100)),
                ('eway_password', models.CharField(blank=True, default='', max_length=255)),
                ('einvoice_username', models.CharField(blank=True, default='', max_length=100)),
                ('einvoice_password', models.CharField(blank=True, default='', max_length=255)),
                ('auth_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_config', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EInvoiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('irn', models.CharField(db_index=True, max_length=64, unique=True)),
                ('signed_invoice', models.TextField(blank=True, default='')),
                ('signed_qr_code', models.TextField(blank=True, default='')),
                ('ack_number', models.CharField(blank=True, default='', max_length=50)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=50)),
                ('cancel_remarks', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einvoices', to='companies.company')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice_record', to='accounting.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='EWayBillRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ewb_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ewb_date', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('EXTENDED', 'Extended')], default='ACTIVE', max_length=20)),
                ('supply_type', models.CharField(default='OUTWARD', max_length=20)),
                ('sub_supply_type', models.CharField(default='SUPPLY', max_length=30)),
                ('doc_type', models.CharField(default='INV', max_length=10)),
                ('transport_mode', models.CharField(choices=[('1', 'Road'), ('2', 'Rail'), ('3', 'Air'), ('4', 'Ship')], default='1', max_length=5)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('transporter_id', models.CharField(blank=True, default='', max_length=15)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('vehicle_type', models.CharField(default='R', max_length=10)),
                ('transporter_doc_no', models.CharField(blank=True, default='', max_length=50)),
                ('transporter_doc_date', models.DateField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=50)),
                ('cancel_remarks', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bills', to='companies.company')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bills', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-ewb_date'],
            },
        ),
    ]
