# Generated by Django 5.2.17 on 2026-09-21 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_voucher_buyer_email_voucher_itc_held_amount_and_more'),
        ('companies', '0013_alter_usercompany_role'),
        ('gst', '0002_alter_gsttaxpayercache_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR2BImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_period', models.CharField(db_index=True, max_length=10)),
                ('financial_year', models.CharField(blank=True, default='', max_length=10)),
                ('file_format', models.CharField(choices=[('JSON', 'GST Portal JSON'), ('EXCEL', 'GSTR-2B Excel'), ('API', 'GSP Direct API')], default='JSON', max_length=10)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_invoices_count', models.PositiveIntegerField(default=0)),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_itc_available', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PROCESSED', max_length=20)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstr2b_imports', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTR2BRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_gstin', models.CharField(db_index=True, max_length=15)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('normalized_invoice_number', models.CharField(db_index=True, max_length=100)),
                ('invoice_type', models.CharField(default='R', max_length=10)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=10)),
                ('reverse_charge', models.CharField(default='N', max_length=5)),
                ('itc_available', models.BooleanField(default=True)),
                ('itc_ineligible_reason', models.CharField(blank=True, default='', max_length=100)),
                ('gstr1_filing_date', models.DateField(blank=True, null=True)),
                ('gstr3b_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched in Books'), ('MISMATCHED', 'Value / Tax Mismatch'), ('MISSING_IN_BOOKS', 'Missing in Purchase Books')], default='MISSING_IN_BOOKS', max_length=30)),
                ('mismatch_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstr2b_records', to='companies.company')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gst.gstr2bimport')),
                ('matched_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gstr2b_matches', to='accounting.voucher')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'supplier_gstin', 'normalized_invoice_number'], name='gst_gstr2br_company_28185a_idx')],
            },
        ),
    ]
