# Generated by Django 5.2.8 on 2026-10-02 09:19

import apps.gst.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_upi_id'),
        ('gst', '0003_gstr2bimport_gstr2brecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygstconfig',
            name='api_key',
            field=apps.gst.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companygstconfig',
            name='api_secret',
            field=apps.gst.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companygstconfig',
            name='auth_token',
            field=apps.gst.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companygstconfig',
            name='einvoice_password',
            field=apps.gst.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companygstconfig',
            name='eway_password',
            field=apps.gst.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='GSTFilingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_type', models.CharField(choices=[('GSTR1', 'GSTR-1 (Outward Supplies)'), ('GSTR3B', 'GSTR-3B (Monthly Summary Return)'), ('GSTR9', 'GSTR-9 (Annual Return)'), ('CMP08', 'CMP-08 (Composition Scheme)')], default='GSTR1', max_length=20)),
                ('return_period', models.CharField(db_index=True, max_length=20)),
                ('financial_year', models.CharField(blank=True, default='', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('SUBMITTING', 'Submitting to Portal'), ('SUBMITTED', 'Submitted'), ('FILED', 'Filed'), ('FAILED', 'Filing Failed'), ('RECONCILIATION_REQUIRED', 'Reconciliation Required')], default='FILED', max_length=30)),
                ('arn', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('invoices_count', models.PositiveIntegerField(default=0)),
                ('filing_mode', models.CharField(default='DIRECT_PORTAL', max_length=30)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_filings', to='companies.company')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['company', 'return_type', 'return_period'], name='gst_gstfili_company_b96b58_idx')],
            },
        ),
    ]
