# Generated by Django 5.2.17 on 2026-09-09 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('companies', '0011_company_deleted_at_company_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='current_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'model_name', 'record_id'], name='audit_audit_company_99a7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'created_at'], name='audit_audit_company_35a24b_idx'),
        ),
    ]
