# Generated by Django 5.2.17 on 2026-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_auditlog_current_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('POST', 'Post'), ('CANCEL', 'Cancel'), ('REVERSE', 'Reverse')], max_length=20),
        ),
    ]
