# Generated by Django 5.2.17 on 2026-10-03 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
        ('companies', '0018_company_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company'),
        ),
    ]
